Feature/loc 510 privacy manager
gimbalinc/rtn-gimbal-sdk pull request #8
Opened 2023-02-03 00:22 UTC by andrew-tran-infillion

Add Android PrivacyManager module.

Add PrivacyManagerSpec for oldarch and newarch.
Add PrivacyManagerModule.
Add PrivacyManagerModule to GimbalPackage.
Fix Sample app _logConsentRequirement method to specify indeterminate requirement.

2023-02-08 17:39 UTC, kimvsparrow requested changes
Almost there!

2023-02-08 17:39 UTC, kimvsparrow commented on ios/RtnPrivacyManager.mm
> +RCT_REMAP_METHOD(getGdprConsentRequirement, getGdprConsentRequirementWithResolver:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
These three aren't compatible with the codegen signatures:
```
- (void)getGdprConsentRequirement:(RCTPromiseResolveBlock)resolve
                           reject:(RCTPromiseRejectBlock)reject;
- (void)setUserConsent:(double)consentType
                 state:(double)state;
- (void)getUserConsent:(double)consentType
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
```
The first one needs to be changed to `RCT_EXPORT_METHOD` and then `getGdprConsentRequirementWithResolver` can be snipped out to leave the resolve. I think for the others, the message names need to match (`reject` instead of `rejecter` etc.)

2023-02-08 17:39 UTC, kimvsparrow commented on ios/RtnPrivacyManager.mm
> +@implementation RCTConvert(GMBLConsentType)
Apparently codegen doesn't support enums in signatures (yet, see https://github.com/reactwg/react-native-new-architecture/discussions/68#discussioncomment-3413488). So I don't think these are used any more.  It might take some manually testing to be sure though.

2023-02-08 17:39 UTC, kimvsparrow commented on src/NativePrivacyManager.ts
> +        CONSENT_STATE_UNKNOWN: Int32,
If I understand this declaration correctly, we're basically saying that `getConstants` is a lambda/closure that returns a type which is defined by all the fields in the curly brackets. Each of those typed fields should be terminated with a `;` (semi colon).

2023-02-08 17:39 UTC, kimvsparrow commented on android/src/oldarch/com/gimbal/rtn/PrivacyManagerSpec.java
> +    public abstract void setUserConsent(int consentType, int state);
The codegen signatures for these two are:
```
  public abstract void setUserConsent(double consentType, double state);
  public abstract void getUserConsent(double consentType, Promise promise);
```

Which hopefully plays okay with a simple cast in the implementations.

2023-02-08 19:40 UTC, andrew-tran-infillion commented on android/src/oldarch/com/gimbal/rtn/PrivacyManagerSpec.java
> +    public abstract void setUserConsent(int consentType, int state);
Android testing looks good so far, but I'll keep this in mind if any weird bugs come up later.

2023-02-10 23:49 UTC, kimvsparrow approved these changes
What a rush!

2023-02-10 23:53 UTC, merged